### ISSUE TITLE
Implement random photo

### ISSUE THREAD

**Issue by dechuck** [CrewLabs/Unsplash-PHP#17]
We can now retrieve a single, random, photo from the API.

https://unsplash.com/documentation#get-a-random-photo

**Comment by freezy-sk** [comment]
@dechuck is there a possibility to set list of usernames or it works only for single one?

**Comment by aaronklaassen** [comment]
@freezy-sk Only for a single username, unfortunately.

**Comment by freezy-sk** [comment]
@aaronklaassen that's a pity :(
