### ISSUE TITLE
API documentation link broken

### ISSUE THREAD

**Issue by sayanb** [CrewLabs/Unsplash-PHP#21]
Hi,

This link https://github.com/CrewLabs/Unsplash-PHP/blob/master/official-documentation takes me to a 404.

Thanks,
Sayan

**Comment by dechuck** [comment]
Hi @sayanb,

Thanks for reporting this issue, I'll fix it right away.
Don't hesitate if you have question about the wrapper or the API.

Thanks,
Charles

**Comment by sayanb** [comment]
Thanks, Charles. 

My aim is to use Unsplash\Photo::search() to search for a user-supplied string, loop through the results and for each of the photos, obtain the full, regular, small and thumb versions. 

I've reached upto this point:

$photos = Crew\Unsplash\Photo::search($searchTerm);
$photos = $photos->getArrayCopy();
		
foreach($photos as $photo) {
    //?
}

Do you have methods to extract the information I need?

**Comment by dechuck** [comment]
Hi @sayanb,

`Crew\Unsplash\Photo::search` return an array of StdClass. So, in your foreach loop, you can retrieve the image paths by doing 

```php
foreach($photos as $photo) {
  $photo->urls["full"];
  $photo->urls["regular"];
  $photo->urls["small"];
  $photo->urls["thumb"];
}
```

You can find all the variables return by the API call [here](https://unsplash.com/documentation#photos).

I hope that answers your question :smiley:
