### ISSUE TITLE
league/oauth2-client ~1.0

### ISSUE THREAD

**Issue by zembrowski** [CrewLabs/Unsplash-PHP#23]
Dear Crew-Team,

when is league/oauth2-client ~1.0 support planned?

I've got another composer package that requires league/oauth2-client in ~1.0 version and both 0.12 and ~1.0 can't be installed at the same time.

I started to define the missing abstract functions which was not difficult, but get stuck with the following error: Cannot access protected property Crew\Unsplash\Provider::$clientId in /vendor/crewlabs/unsplash/src/Connection.php on line 94

Would appreciate an answer.

Thanks in advance.

Best regards,
Krzysztof

**Comment by dechuck** [comment]
Hey @zembrowski,
I will update the package today. I'll let you know when it will be done. 

Thanks,
Charles

**Comment by dechuck** [comment]
@zembrowski 
I just open a PR with the new version of OAuth2-client. Don't hesitate to take a look before I merge it.
#24

**Comment by zembrowski** [comment]
Awesome! Just tested it. Works for me.

Three things came to my attention:
1. There is no setScopes function in the Provider. So when you set Crew\Unsplash\HttpClient::$connection->getConnectionUrl(['public']); you'll get an error coming from line 32 of the Connection file.
2. Why is the default scope public and read_user?
3. Would it make sense to set the URIs in constants like in https://github.com/thephpleague/oauth2-facebook/blob/master/src/Provider/Facebook.php?

And the last one: maybe it makes sense to get in touch with the creators of the oauth2-client to get listed on the provider list cf. https://github.com/thephpleague/oauth2-client/blob/master/README.PROVIDERS.md

Cheers,
Krzysztof

**Comment by dechuck** [comment]
@zembrowski 
Thanks for the quick feedback. 

> 1. There is no setScopes function in the Provider

I will fix the issue with the setScopes.
OAuth2-client did a lot of change in the last version, I miss this one. I'll make sure also to have a test for this issue.

> 2. Why is the default scope public and read_user?

I set `read_user` by default to be sure `getResourceOwner` from `League\OAuth2\Client\Provider\AbstractProvider` works out of the box, but I don't think it's necessary. I will remove `read_user` from the default scope and add a not in the documentation.


> 3. Would it make sense to set the URIs in constants

It think it would. 

Thanks a lot for your time. I'll fix the last issues tomorrow and let you know when it's merged.

**Comment by dechuck** [comment]
Thanks for your help @zembrowski 
I merge the PR and update the version to `1.1.0`.
