### ISSUE TITLE
Fix test in codeship

### ISSUE THREAD

**Issue by dechuck** [CrewLabs/Unsplash-PHP#7]
Even if my cassette are present, codeship seems to want to do the request.

If I'm change my testing variable that set the api url from `api.lvh.me` to `api.staging.unsplash.com` my test seems to work, but codeship run the API call on his side, since the request uri change.

**Comment by aaronklaassen** [comment]
I was actually about to bring this up, but all the URL's in `Provider` are referring to staging. Is that a (or *the*) bug?

**Comment by dechuck** [comment]
So, for the `api.staging.unsplash.com` in the code, I'm waiting for the production release of the API to change that and release the version 1 of the wrapper.

I created a method that set the URI and Scheme, to be able to test more easily (https://github.com/CrewLabs/Unsplash-PHP/blob/master/src/HttpClient.php#L113), I realized that in codeship if my ENV_MODE is at test, and that the API_URI is api.lvh.me, it's not seems to work, but it's working well if API_URI is at api.staging.unsplash.com

I think that, even if I'm having cassettes, codeship try to execute the query, and lvh.me redirect to the localhost of codeship. But since my cassettes are doing request to lvh.me domain, I need to set the same one on codeship, to be sure it's the same request as the cassette. But it seems that doesn't work.

**Comment by dechuck** [comment]
I fix the issue. Php-VCR was matching all the request parts to know if it should use the cassette or not. So, I change the validation and I don't use the header to do the validation. Now it's work.

**Comment by lukechesser** [comment]
Good change abstracting the `$host` out. I was gonna suggest that.

**Comment by dechuck** [comment]
Actually, I was thinking to get rid of the host too. 
So it would do the validation on the `method, url, body, query_string` + the custom matcher for the authorization header.

**Comment by lukechesser** [comment]
Yeah, whatever you think works the best. But I remember making a note that `api.unsplash.com` shouldn't be repeated in every method, so this is definitely better 👍

**Comment by dechuck** [comment]
This was fix 2-3 weeks ago :smile: 
I use a environnement config now. The only place you could find it now, it's the cassettes.
